name: runs the main python file

on:
  schedule:
    - cron: "0 */3 * * *"    #runs every 3 hours once

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo dev
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v4

        with:
          python-version: 'latest'
      
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install - r requirements.txt

      - name: Execute the python scripts
        env: 
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: python main.py

      - name: commit files
        run: |
          git config --local user.email "venkatasairam.y@gmail.com"
          git config --local user.name "venkat-sairam"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "updated logs" --allow-empty)

      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main 
          
        
